arch:
  type: TransformerLMHeadModel
  args:
    transformer_config:
      type: TransformerDecoderOnlyModel
      args:
        embed_config:
          type: TransformerEmbedding
          args:
            do_ln: True
            p_drop_embed: 0.1
        decoder_config:
          type: TransformerDecoderBlock
          args:
            attn_config:
              type: MultiHeadKeyValueAttention
              args:
                p_drop_attn: 0.1
                p_drop_resid: 0.1
                bias_attn: True
                bias_proj: True
                cross_attn: False
                scale_dot_product: True
                scale_layer_wise: False
                perform_linear_bias: True
                perform_bloom_split_head: False
            mlp_config:
              type: TransformerMLP
              args:
                act_fn:
                  type: BloomGelu
                  args: {}
                p_drop_mlp: 0.1
    lm_head_config:
      type: TransformerLMHead
      args:
        do_transform: False

models:
  bloom-560m:
    n_embed: 1024
    n_layer: 24
    n_head: 16
    head_size: 64
    n_inner: 4096

global_params:
  n_vocab: 250880
  n_pos: 0
  perform_linear_bias: True
  perform_bloom_split_head: True
