arch:
  type: TransformerLMHeadModel
  args:
    transformer_config:
      type: TransformerDecoderOnlyModel
      args:
        embed_config:
          type: TransformerEmbeddingBlock
          args:
            token_embed_config:
              type: TokenEmbedding
            p_drop_embed: 0.0
        decoder_config:
          type: ParallelTransformerDecoderBlock
          args:
            attn_config:
              type: GPTNeoXAttention
              args:
                p_drop_attn: 0.0
                p_drop_resid: 0.0
                bias_attn: True
                bias_proj: True
                cross_attn: False
                scale_dot_product: True
                scale_layer_wise: False
                rope_config:
                  type: MistralRotaryEmbedding
            mlp_config:
              type: TransformerMLP
              args:
                n_embed: ~
                n_inner: ~
                act_fn_config:
                  type: NewGELUActivation
            ln_config:
              type: LayerNorm
            share_layer_norm: True
        ln_config:
          type: LayerNorm
    lm_head_config:
      type: TransformerLMHead
      args:
        bias_lm_head: True
        do_transform: False

models:
  microsoft/phi-1_5:
    n_embed: 2048
    n_layer: 24
    n_head: 32
    n_key_value_head: 32
    head_size: 64
    n_inner: 8192
    rotary_head_size: 32

global_params:
  n_vocab: 51200
  n_pos: 2048
  ln_eps: 1.0e-05
