models:
  gpt2-base:
    path: ~
  gpt2-medium:
    path: ~

model_args:
  pretrained_model_name_or_path: ~
  use_fast: True
  trust_remote_code: True
  list: [1, 2, 3, 4]
  type: BertForCausalLM
  ln_eps: 1.0e-5
